[package]
name = "theos-compositor"
version = "0.1.0"
edition = "2024"

[features]
default = ["compositor"]
compositor = [
    "dep:smithay", "dep:input", "dep:wayland-server",
    "dep:calloop", "dep:libc", "dep:drm", "dep:gbm",
    "dep:khronos-egl", "dep:nix"
]

[dependencies]
chacha20poly1305 = "0.10"
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
sha2 = "0.10"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
theos-core = { path = "../theos-core" }
tokio = { version = "1.49.0", features = ["full"] }
calloop      = { version = "0.14.4", optional = true }
input        = { version = "0.9.1",  optional = true }
libc         = { version = "0.2.182", optional = true }
smithay      = { version = "0.7.0", features = ["desktop", "wayland_frontend", "renderer_gl"], optional = true }
wayland-server = { version = "0.31.11", optional = true }
drm          = { version = "0.14", optional = true }
gbm          = { version = "0.18", optional = true }
khronos-egl  = { version = "6", features = ["dynamic"], optional = true }
nix          = { version = "0.29", features = ["fs", "ioctl"], optional = true }
